export const UPDATE_BUY_NUM = 'UPDATE_BUY_NUM';
export const UPDATE_TRANSFER_NUM = 'UPDATE_TRANSFER_NUM';
export const UPDATE_MESSAGE_COUNT = 'UPDATE_MESSAGE_COUNT';
export const UPDATE_TREASURE_BOX_UNFINISHED_COUNT = 'UPDATE_TREASURE_BOX_UNFINISHED_COUNT';
